spring:
  application:
    name: pathfinder-helper

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pathfinder_helper_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate  # ???????? ????? ?????? ????? environment
    properties:
      hibernate:
        show_sql: false  # ? dev SQL-??????? ?? ????????

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml  # ???????, ??? ???? ?????? ?????????