package ru.hackass122.pathfinderhelper.common.enums;

public enum EffectType {
    BONUS,
    LANGUAGE_GAIN,
    SENSE_GAIN,
    STRIKE_MODIFICATION,
    MOVEMENT_MODIFICATION,
    GRANT_ABILITY,
    CLASS_FEATURE_MODIFICATION,
    EQUIPMENT_ACCESS,
    REQUIREMENT_REMOVAL,
    SKILL_PROFICIENCY_INCREASE,
    SAVE_THROW_PROFICIENCY_INCREASE,
    PERCEPTION_PROFICIENCY_INCREASE,
    WEAPON_PROFICIENCY_INCREASE,
    ARMOR_PROFICIENCY_INCREASE,
    SPELL_PROFICIENCY_INCREASE,
    FEAT_UNLOCK
}
